services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=postgres://admin:admin@db:5432/avito?sslmode=disable
      - POSTGRES_JDBC_URL=jdbc:postgresql://db:5432/avito
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=avito

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=avito
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
